### ISSUE TITLE
Add NAG PAM to the website

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#22]
It is currently mentioned in the main text that it is possible to search for NAGs, but there's no such option in the website.

**Comment by HyamsG** [comment]
Hi Shlomzion - when calling to the function, please add another parameter at the end of the parameters given to the function. value of 0 means PAM = 'NGG', value of 1: 'NGG' or 'NAG'. value of 2: 'NAG'.

the up to date parameters list, when calling the function:
(fasta_file, path , alg = 'A', where_in_gene = 1, use_thr = 0,  Omega = 1, df_targets = Metric.cfd_funct, protodist_outfile = "outfile", min_length= 20, max_length = 20,start_with_G = False, internal_node_candidates = 10, PS_number = 12, PAMs = 0)

note that all my changing so far are in the code at this path:
/groups/itay_mayrose/galhyams/CRISPys_revision_25_12

In order to avoid inserting bugs that might interrupt with your work.

Let me know of any question

Gal

**Comment by shiranab** [comment]
PAM sequence: 
1. NGG    (value=0)
2. NGG or NAG    (value=1)


Gal, it has to be added as an input parameter to the argparse

**Comment by shiranab** [comment]
Can be closed?
