### ISSUE TITLE
analyze clustering method

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#6]
should show how we obtained significantly different results when the UPGMA tree was obtained with 2 different distances. Once this is done, we should think about the answer to referee 1.

**Comment by HyamsG** [comment]
so significant difference:

כאשר משתמשים בבסיס מטרות, אין הבדל משמעותי אם מדובר במרחק אוקלידי או מנהטן:

avg=  0.005152763788613195
std=  0.026334038346358835


לטובת אוקלידי
וזה ההבדל לטובת ה"80-mer", מרחק אוקלידי, ביחס לאוקלידי על המרחק מהמטרות
avg=  -0.002720981984020655
std=  0.024576813682959664
;
I think that the comparison the ref. wanted is between Hierarchical clustering and something like k-means. He is right - I've put a file in the dropbox of things to add to the text, but I'll add only after someone will go over it, to prevent 'double workings'. I'll add to the file the explanation about controlling the num. of polimorphic sites, which is possible with Hierarchical clustering but not with K-means.

**Comment by HyamsG** [comment]
Compering Hierarchical clustering and NJ, NJ got slightly better results, but far from being significant: 
avg=  -0.001220336570081244
std=  0.006817568518953049

**Comment by shiranab** [comment]
what are these numbers? avg and std of what?

**Comment by HyamsG** [comment]
Computed again:
the average and std in the normalized difference in the score of the best sgRNA candidate.  The normalized difference means that the difference was divided in the score itself the score of the best sgRNA by the default method, which is Hierarchical clustering in this case. 
I should have given the credible interval instead of the variance. I had a bug and computed again. got avg of 4.513*e-19 (to the hierarchical clustering over the NJ) and std 5.48*e-17, but I want to make sure that when python writes e^-17 it does not mean to 10^-17. Will compute the Credible interval after finding this point out..

In addition, I really want to add the article I've sent you as a ref. to the work. It gives a firm ground to the choice of the Hierarchical clustering as the clustering method. Let me know if you want me to write it.

**Comment by HyamsG** [comment]
the margins of the confidence interval:
4.513e-19 +- 2.450805e-18
meaning, 0 is in the confidence interval, hence the difference is not significant
